"""Add new features

Revision ID: 8fc6054da1fa
Revises: 
Create Date: 2026-04-24 16:56:37.527335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc6054da1fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('type', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('color', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('note', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('monthly_budget', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.drop_column('users', 'monthly_budget')
    op.drop_column('users', 'name')
    op.drop_column('subscriptions', 'note')
    op.drop_column('subscriptions', 'category')
    op.drop_column('subscriptions', 'icon')
    op.drop_column('subscriptions', 'color')
    op.drop_column('expenses', 'type')
    # ### end Alembic commands ###
